### PR TITLE
Manual sync with original reactjs repo

### PR DESCRIPTION
**Pull request by arshadkazmi42**

### CODE REVIEW

**Comment by arshadkazmi42** [comment]
> This file has outdated code (this import doesn't exist in main):
> 
> Screenshot 2022-02-18 at 19 19 08

@gaearon Change this file fixed one of the failing tests, I am seeing there are still 3 more tests which are failing. Can you check and let me know, what is causing those to fail?

**Comment by arshadkazmi42** [comment]
@gaearon 
Found the issue in one of MD file related to translations. Fixed.
Now only the ci builds are failing. Can you check once and let me know what could be causing that

**Comment by saranshkataria** [comment]
@arshadkazmi42 I see that CircleCI was removed from the reactjs.org repo here: https://github.com/reactjs/reactjs.org/pull/4236
Removed the webhook and deleted the key for deployment as well

**Comment by saranshkataria** [comment]
Also, I see the need for manual syncing was caused because we merged dependabot's PR's. In the future, we should probably do that on the reactjs.or repo and let it trickle down to avoid having to do this manually

**Review by saranshkataria — APPROVED** [review]

**Comment by arshadkazmi42** [comment]
Thank you @saranshkataria @gaearon 
With manual sync and some manual fixes and removing cicrle-ci fixed all of the build issues. :tada: 
I have also disable Dependency security alerts for this repository, so we won't get any PRs for updating package versions.

**Pull request merged**
