### PR TITLE
Fix component transliteration

### PR DESCRIPTION
**Pull request by siddharthkp**
Hi!

I think the right transliteration of component is:

```diff
- कौम्पोनॅन्ट
+ कॉम्पोनेन्ट
```

because it's not komponent, it's  kaumponent? [the pronunciation](https://translate.google.com/#view=home&op=translate&sl=hi&tl=en&text=%E0%A4%95%E0%A5%89%E0%A4%AE%E0%A5%8D%E0%A4%AA%E0%A5%8B%E0%A4%A8%E0%A5%87%E0%A4%A8%E0%A5%8D%E0%A4%9F) might help convey what I'm trying to say.

---

1. Confirmed with [Google input tools](https://www.google.co.in/inputtools/try/)

2. Google translate agrees:

screenshot 2019-02-27 at 11 00 51 am

(I don't know if we can trust transliteration tools though, it's always subjective?)

---

This is pretty much in every page

cc: @saranshkataria @arshadkazmi42 @tesseralis

### CODE REVIEW

**Comment by kashishgrover** [comment]
मज़े ले रहे हो यार तुम तो

**Comment by arshadkazmi42** [comment]
My personal opinion on this is, using any of these are fine, it just needs to convey the correct meaning as we not translating it. 
Just writing the pronunciation in hindi can be in different spelling as many people pronounce same words differently.
@saranshkataria Can you have a look at this!

**Comment by siddharthkp** [comment]
@arshadkazmi42 💯 I totally agree with you, please don't spend too much time on this

There's some value in correctness while doing translation/transliteration, but you it's pretty tiny at this stage of the project

**Comment by arshadkazmi42** [comment]
> @arshadkazmi42 100 I totally agree with you, please don't spend too much time on this
> 
> There's some value in correctness while doing translation/transliteration, but you it's pretty tiny at this stage of the project

I think we can close this PR for now.
Also if you would like to contribute to this repo, we have alot of pages pending to be translated you can pick 1 from #1

**Comment by saranshkataria** [comment]
I think either of them is fine and we can just move ahead with what we have decided. Getting into such semantics and discussions will only increase the debate and such arguments won't be of much help especially when they are just slightly off. Closing this out. Hope you can help in translating other pages 😄

**Comment by tesseralis** [comment]
As long as you choose one, put it in the glossary, and stick with it. Also, if you decide to change the spelling later, is should be easy to do a find-replace for the word, right?

**Comment by arshadkazmi42** [comment]
:100:

**Comment by saranshkataria** [comment]
> As long as you choose one, put it in the glossary, and stick with it. Also, if you decide to change the spelling later, is should be easy to do a find-replace for the word, right?

it already was in the glossary. So we are good there.

**Comment by paramaggarwal** [comment]
Please go with `कॉम्पोनेन्ट`. The pronunciation of `कौम्पोनॅन्ट` is completely off.

कॉम्पोनेन्ट  - KOMPONENT
कौम्पोनॅन्ट - KOUMPONENT

**Comment by arshadkazmi42** [comment]
@paramaggarwal We have already discussed about this. For now we are keeping it `कौम्पोनॅन्ट` and later if we plan to change it, it will be just find and replace all.
Right now, priority for us is to get everything translated, later we can work on fixing these types of small things.

**Comment by paramaggarwal** [comment]
> Right now, priority for us is to get everything translated

Yeah, makes sense!

**Pull request closed without merging**
