### PR TITLE
corrected the spelling of क्योंकि

### PR DESCRIPTION
**Pull request by imyogeshgaur**

### CODE REVIEW

**Review by arshadkazmi42 — APPROVED** [review]
:+1:

**Comment by arshadkazmi42** [comment]
@imyogeshgaur Seems the build is failing, can you update the PR. Also can you sync it with latest main branch. The changes looks good. once the build issue is fixed, We can get this merged.

**Comment by arshadkazmi42** [comment]
@imyogeshgaur Please ignore the previous comment. I have updated it. Merging.

Thanks for working on this :+1:

**Comment by imyogeshgaur** [comment]
@arshadkazmi42  Thank you 😊

**Pull request merged**
