### PR TITLE
Translated one paragragh

### PR DESCRIPTION
**Pull request by Anishpras**

### CODE REVIEW

**Comment by arshadkazmi42** [comment]
Hi @Anishpras 

Thank you for this PR.

But this page is already taken up and there is a PR in review here https://github.com/reactjs/hi.reactjs.org/pull/169

Can you pink some other page from this list https://github.com/reactjs/hi.reactjs.org/issues/168

I have updated the list and marked the name of users who are working on the page.

So you can pick a page where no user is assigned.

Closing this PR.

**Comment by Anishpras** [comment]
Can I work on the "Add React to a website" page?

**Comment by arshadkazmi42** [comment]
Sure. Go ahead. I have assigned you the page

**Comment by Anishpras** [comment]
Thankyou! Have created a PR [#172](https://github.com/reactjs/hi.reactjs.org/pull/172) for it.

**Pull request closed without merging**
